server:
  port: 9000

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/workplace?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


# mybatis
mybatis:
  type-aliases-package: org.maogogo.shopping.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 100

# jdbc
